### ISSUE TITLE
Requests to Meetup API are missing headers

### ISSUE THREAD

**Issue by ramonaspence** [codeforgreenville/upstate_tech_cal_service#40]
I just noticed that the requests to Eventbrite are using headers for authorization. Do the requests to Meetup's API not require any headers for the sake of authorization? 

I bring this up because when I go to the Meetup API endpoint that's used in App.py I get this output:
`{"errors":[{"code":"auth_fail","message":"Invalid csrf credentials"}]}`

**Comment by allella** [comment]
@ramonaspence check out this [old issue about Meetup v2 vs v3](https://github.com/codeforgreenville/upstate_tech_cal_service/issues/20#issue-488936889).

I believe we changed the URLs to use the v3 API, but since we're only doing GET requests which are publicly available, I don't think we needed to setup OAuth to make those base requests.

Do you think something you were doing was hitting a v2 API OR trying to pass the &key=  GET parameter which is now deprecated?  We were using key={a value from config.ini} but we simply removed it and started using v3 public GET requests.

**Comment by ramonaspence** [comment]
Oh I see. So, it was actually an invalid "group name" that I was giving the url. 

`meetup.api.com/Hack-Greenville/events` works for example but, 
`meetup.api.com/1234567890/events` does not work. 

So no issue with the headers then.

**Comment by allella** [comment]
Nice. Do we need to keep this issue open, or is it good now?

**Comment by ramonaspence** [comment]
We're good now 👍🏻
