### ISSUE TITLE
Update Python modules and Document the Process For Adding, Changing, or Updating with Miniconda

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#45]
As per https://github.com/codeforgreenville/upstate_tech_cal_service/pull/44#issuecomment-1029548202, we may have some issues from the app being pinned to Python 3.6 when running Docker mode.

- [ ] Remove step 4 about chmod +x in deploy_notes_updates.md
- [ ] Add a step about how to keep Minconda up to date after Git pulls in deploy_notes_updates.md
- [ ] Update Python modules to the latest (probably best to make this a separate PR)

For example, I have 3.9 installed on my computer and I guess Docker isn't using the virtual Miniconda environment, or something like that, because I get the _is_xhr_ issue only when running through Docker.

> upstate-tech-cal-server    |   File "/app/app.py", line 363, in get_dates
> upstate-tech-cal-server    |     return jsonify(events)
> upstate-tech-cal-server    |   File "/opt/conda/envs/cal_service/lib/python3.6/site-packages/flask/json.py", line 251, in jsonify
> upstate-tech-cal-server    |     if current_app.config['JSONIFY_PRETTYPRINT_REGULAR'] and not request.is_xhr:
> upstate-tech-cal-server    | AttributeError: 'Request' object has no attribute 'is_xhr'
> 

Running `gunicorn --bind 0.0.0.0:8000 app:app` works without the 'is_xhr' error.

**Comment by allella** [comment]
We determined `conda env update --file environment.yml --prune` is the command to update the environment.  Does that need to always be run after a `conda activate cal_service`, or does it not matter if you're "in" the virtual shell?

What's the way to add a new module?  `conda install -n cal_service module_name`?

**Comment by allella** [comment]
I'm not too in love with a bunch of randomly named docs files, so we might eventually consolidate all docs to a [CONTRIBUTING.md that has collapsed sections](https://github.com/allella/chapter/blob/main/CONTRIBUTING.md).

Though for now, it would be nice to get things "down on paper" and then worry about prettying and consolidating.

This is what we've used to note how to deploy code to the live server, but it also roughly applies if someone is pulling down new commits.

Can we safely always run a Miniconda update command `conda env update --file environment.yml --prune` after any git pulls?

Also, I don't think the current step 4 is necessary and it may not even be correct since I don't think you need execute permissions on a script since you're actually executing python and it's reading the script.  If we did need a chmod +x it would be a one-time thing and and needed on every update.

> Make update_cal_data.py executable: chmod +x update_cal_data.py

**Comment by ramonaspence** [comment]
> We determined `conda env update --file environment.yml --prune` is the command to update the environment. Does that need to always be run after a `conda activate cal_service`, or does it not matter if you're "in" the virtual shell?
> 
> What's the way to add a new module? `conda install -n cal_service module_name`?


I think that the `conda env update` command can be run with the environment active or not. For me, it seemed to have worked fine when the environment was active, but [this stackoverflow answer](https://stackoverflow.com/a/46114295/13984303) says it should be deactivated first.

[Here's a stackoverflow answer](https://stackoverflow.com/a/43873901/13984303) that details the --prune flag a little better.


To add a new module, we need to first update the environment as described above. Once the environment is up to date, we can actually just use `pip install <package_name>` since pip is installed in the environment. The package then needs to be added to `environment.yml` so that the next time we run the `conda env update` command, it'll include the new package. 

We can also install it via [conda install](https://docs.conda.io/projects/conda/en/latest/commands/install.html) if that's applicable, but if it's a python module, I'm not sure if there is a reason to use one over the other.

One thing to add: the only problem the command `conda env update --file environment.yml --prune` might cause is uninstalling a package that has been installed in the environment but not yet added to `environment.yml`. However, the fix there should simply be to add it to `environment.yml` and run the command again OR installing the package again *and* adding it to `environment.yml`.


One more thing before a sign off: 
Would it be beneficial to separate the steps for production/remote servers and the steps for a local server? It seems like they are different enough that it may be more legible. 

It's going to look so nice when the docs are in one file with the collapsible sections :grin:

**Comment by allella** [comment]
Thanks @ramonaspence 

Alright, it seems odd you'd need to run pip and conda.  If we add required packages to the environment.yml and run conda update, then is that sufficient to bring things up to speed with any new versions and new modules?

My expectations are based on PHP's composer.json and Node / npm's package.json.  I assume environment.yml works in a similar fashion where you can pin specific versions, or min / max semantic versions and then running a command will install anything that's missing and bring any other packages up to date based on what the file specifies.

Composer and npm also have a .lock file, which makes sure an exact configuration is locked.  In PHP a "composer install" doesn't actually 'install' anything. Rather, it updates based on a lock file.  Running composer update will actually fetch the latest versions of the packages that meet the criteria of the composer.json.  

I assume pip and Python operate in a similar fashion.  Does pip have a lock file equivalent?

**Comment by ramonaspence** [comment]
You're right, it does seem kind of odd. After doing some reading, it seems like using conda and pip together isn't the usual choice. 

I wonder if the `environment.yml` would look different if we were to uninstall Pip and install the Python packages through [conda's packages](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-packages). I think Pip wouldn't be in the env.yml file and the other packages would not be indented. 

How it looks now:
```
dependencies:
  - python=3.6
  - pip
  - gunicorn
  - pip:
    - Flask==0.12.2
    - simplejson==3.11
  
 ```
    
If we uninstalled the packages listed under `Pip` in the `environment.yml` and installed the same packages through Conda, instead of Pip, then created another `envmironment.yml` file, it may streamline the setup and update of the environment.

We could also include docs for how to install new packages by [searching anaconda.org](https://anaconda.org/search?q=flask) and/or point to the documentation for [searching for packages on the command line](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#using-packages)

I think the other direction would be using pipenv for an environment and as a package manager. Pipenv also uses a `Pipfile` and `Pipfile.lock` files that would be the "pip" version of composer. I would checkout this [Stack Overflow answer](https://stackoverflow.com/a/49867443/13984303) but the whole question as well, to get a better idea of pipenv in this context. 

And I'm just throwing out thoughts here at 1am lol

EDIT: added link to stackoverflow

**Comment by ramonaspence** [comment]
> You're right, it does seem kind of odd. After doing some reading, it seems like using conda and pip together isn't the usual choice.
> 
> I wonder if the `environment.yml` would look different if we were to uninstall Pip and install the Python packages through [conda's packages](https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#conda-packages). I think Pip wouldn't be in the env.yml file and the other packages would not be indented.
> If we uninstalled the packages listed under `Pip` in the `environment.yml` and installed the same packages through Conda, instead of Pip, then created another `envmironment.yml` file, it may streamline the setup and update of the environment.


(On a new branch just for this) I have uninstalled the python packages, including Pip and then reinstalled using `conda install`. 

Here's what the `environment.yml` file looks now:
```
name: cal_service
channels:
  - defaults
  - conda-forge
dependencies:
  - conda
  - python==3.6
  - flask==0.12.2
  - flask-restful
  - requests==2.22.0
  - simplejson==3.11.1
  - python-crontab==2.5.1
  - pytz==2017.3
  - flask-cors==3.0.3
  - gunicorn
prefix: /Users/admin/miniconda3
```

The `channels` specifies where the conda package resides. 
I went ahead and tested this in Postman and I don't see any changes to the functionality (I tested the returned content-type, the tag filtering and the date filtering, both in json and json+ld).

I'm admittedly learning about conda as I go, so I don't personally know if this is better than the current environment.yml that uses Conda to install Pip and then uses Pip to install the python dependencies.

**Comment by ramonaspence** [comment]
If we continue to use Conda and Pip side by side, adding a new python package would still be done using `Pip install`, and if there are any non-python packages to add to the project, that would be done with `conda install`. 

I don't know what would be best for us to do, but I'm hoping I've laid it out well enough for us to see which direction to move forward with.

**Comment by allella** [comment]
Thanks. I read a bit on it and I'm not sure what we're gaining from Conda over pipenv or virtualenv (whatever the core Python is these days).

Miniconda may have been used by the original dev to learn a new tool.

I personally don't care for the [activate and deactivate stuff and the sub-shell](https://stackoverflow.com/a/49867443), so I wouldn't be opposed to going back to regular Python if you want to give that a go.

> Pipenv handles the virtual environment for you in one default standard way (no more activate and deactivate required). Below, some basics to get you started, see more at pipenv website.

**Comment by ramonaspence** [comment]
Okay, I'll set up my local environment with Pipenv, get a `Pipfile` and `Pipfile.lock` generated and then I'll make the edits on the documentation.

I'm sure I'll need a good review and edit on the changes I make to the documentation. I'm guessing that can be done when a PR is made?

I think this will make it easier for Python folks to jump into the project and since it's all Python, I'm not sure it's benefitting us more than Pipenv will.

**Comment by allella** [comment]
Yeah, is Pipenv the current default?  I'm not a Python dev so double-check anything I say / suggest.

**Comment by ramonaspence** [comment]
Yes, I would consider Pipenv the standard. The [first section](https://pipenv.pypa.io/en/latest/#pipenv-python-dev-workflow-for-humans) gives a far better summary than I could.

**Comment by ramonaspence** [comment]
And yeah, I do a lot of reading in between our messages because I'm still learning quite a lot myself

**Comment by allella** [comment]
Sounds good.

I'm familiar with composer and npm + nvm, so it seems this fits the typical pattern where conda was solving other problems we mostly didn't have.

Thanks for the link.

**Comment by ramonaspence** [comment]
What I've done:

1. Removed conda environment

**Comment by ramonaspence** [comment]
I'll have this wrapped up soon. I'm going to review what I've done tomorrow morning and then make a PR for the switch to Pipenv and the related edits to the documentation.

p.s.
The changes I've made for this so far:
   - Deleted Conda environment and related files (I can provide details on how to do this for anyone wanting to switch locally instead of starting a new fork)
   - Installed Pipenv and all packages that were listed in `environment.yaml`
   - Created a Pipfile and Pipfile.lock
   - Edited `deploy_notes_initial.md` to include instructions on installing Pipenv, creating the environment and installing packages. I've also edited a couple of the steps, replacing Conda commands with the relevant Pipenv commands.
   - Edited `deploy_notes_updates` to change Conda commands to the relevant Pipenv commands.
   - Removed step 4 in `deploy_notes_updates` as you mentioned.     

Once I add steps for updating dependencies and adding new packages, I believe that would close this issue. But correct me if I missed something. 

Edit:
One thing I did overlook in the original post in this issue was updating the python modules. I will look at what versions I installed with pipenv and update whether they are most up to date.

**Comment by allella** [comment]
Thanks for the continued effort on this one.

I think the Conda replacement will simplify things for Python and non-Python devs alike.

**Comment by ramonaspence** [comment]
@allella 
Alright, so I did check the versions of the packages in the Pipfile.lock and they are all up to date. I've tested this in Postman briefly, so nothing is broken. 

I'm not sure I understand what `deploy_notes_updates.md` is describing. It looks like it's describing how to deploy the app to a production site. So I think that's something we can look into when we're editing the docs more heavily. 

I'm going to open a pull request for this and I will detail how to switch from conda to pipenv for anyone who already has the project locally and needs to remove the conda environment.

**Comment by allella** [comment]
Yes, the deploy_notes_updates.md was for production and does need updating at some point.  I'd eventually like to get everything into the README.md and CONTRIBUTING.md because all these other files are using names that are not common.

**Comment by ramonaspence** [comment]
I think thats a great idea. Should we resolve this issue and make another for re-organizing and adding to the documentation?

**Comment by allella** [comment]
Yes, we can revamp the docs in another PR, but if you want to push a commit to address the install and bullet point notes I made, then I think this is ready after that.

Thanks

**Comment by ramonaspence** [comment]
@allella 
I thought I responded to your comment here but I didn't, just on the PR, whoops.

I did get the chance to commit those changes though.

**Comment by allella** [comment]
@ramonaspence alright, I think I got this working on the production server.

It was a bit of a pain because it's CentOS 7 and that has Python 2 by default and I had 3.6 (now EOL) installed as a Linux Software Collection, but I think that was too old for pipenv to install.

More than you need to know, but I was able to do 
sudo yum --enablerepo=centos-sclo-rh -y install rh-python38
scl enable rh-python38 sh

to get to a Python 3.8 shell.  Then, the pipenv install worked.

My main question is what is the 3.9 doing in the Pipfile?

I can't install Python 3.9 without manually compiling and installing and I'd rather stick with the 3.8 version since it's using the Linux package manager / standard.

Also, the `pipenv shell && python update_cal_data.py && exit` seemed to do weird things on this server and running commands inside of a crontab (Cron Job) shell can do weird things, so I'm probably going to go with

`pipenv run python update_cal_data.py` in the Cron

**Comment by allella** [comment]
The cron job that I think is working ends up looking like

`40 * * * * cd /home/username/upstate_tech_cal_service && /home/username/.local/bin/pipenv run python update_cal_data.py`

**Comment by allella** [comment]
Might have been better if I used [pyenv](https://github.com/pyenv/pyenv) to get a later version of Python 3, but the SCL seems to work on 3.8, so not sure I'm going to press my luck.
