### ISSUE TITLE
In-Person Eventbrite Events are Missing service and service_id

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#55]
@ramonaspence per the conversation on the HG https://github.com/codeforgreenville/hackgreenville-com/issues/113

I see that the Tech After Five - Charlotte (In Person) and the latest What's Brewing Greenville? event, which is a new org and new event as of last night, are the only two missing the _service_ and _service_id_ values in the events API.

I suspect this is an easy fix, but since the Tech After Five - Charlotte (In Person) was part of the most recent https://github.com/codeforgreenville/upstate_tech_cal_service/pull/54 I wanted to loop you in.

![image](https://user-images.githubusercontent.com/1777776/166712402-30308ca8-1781-4a99-9676-e17c8ff57af2.png)

![image](https://user-images.githubusercontent.com/1777776/166712739-4e896d65-76b9-4888-9141-48a416c37f75.png)

**Comment by allella** [comment]
This may be a simple as the  if / elif logic is only defining sevice_id and service for online Eventbrite events.

https://github.com/codeforgreenville/upstate_tech_cal_service/blob/master/update_functions.py#L182

Also, the only difference between that if and elif block is the value set for the _venue_, _service_, and _service_id_

Perhaps we can refactor that code to be less repetitive and only use the if / elseif for setting the differences. 

```
event_dict = {
    'event_name': event.get('name').get('text'),
    'group_name': group_name,
    'url': event.get('url'),
    'time': event.get('start').get("utc"),
    'tags': tags,
    'rsvp_count': None,
    'created_at': event.get('created'),
    'description': event.get('description').get('text'),
    'uuid': unique_id,
    'nid': nid,
    'data_as_of': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
    'status': normalize_eventbrite_status_codes(event.get('status'))
}

if type(event.get('venue_id')) == str:

# set the                    'venue': venues[event.get('venue_id')],

}
elif event.get('venue_id') == None: # if event venue is None, it is online/virtual

# set the            'venue': event.get('venue_id'),
}
```

**Comment by allella** [comment]
Here's a `git diff` of a patch I did on the production events API and it seems to fix the issue.

The question is if there's any reason the _service_id_ values would differ between in-person and online Eventbrite events, which I don't think would be the case since we're using the event's unique ID value.  That value is in the Eventbrite URL, so it's not going to change once the event is created

`https://www.eventbrite.com/e/631-tech-after-five-charlotte-in-person-tickets-327548736087`

and

```
service_id | "327548736087"
service | "eventbrite"

```


```
diff --git a/update_functions.py b/update_functions.py
index 9beb240..96ab057 100644
--- a/update_functions.py
+++ b/update_functions.py
@@ -224,7 +224,9 @@ def format_eventbrite_events(events_list, venues_list, group_list):
                     'uuid': unique_id,
                     'nid': nid,
                     'data_as_of': datetime.datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
-                    'status': normalize_eventbrite_status_codes(event.get('status'))
+                    'status': normalize_eventbrite_status_codes(event.get('status')),
+                    'service_id': event.get('id'),
+                    'service': 'eventbrite'
                 }
             elif event.get('venue_id') == None: # if event venue is None, it is online/virtual
                 event_dict = {

```

**Comment by ramonaspence** [comment]
I see that the `format_eventbrite_events` function is just missing the service_id and service fields for in-person events. You're right that it needs to be refactored. It'll be easier for me to see what's going on in the function once it's refactored too. 

I'll jump on it this week :)

**Comment by ramonaspence** [comment]
@allella 

While I'm refactoring this so it's not repeating itself, I thought I would go ahead and do the same for the `format_ld_json` function as well. As of right now, it's using a redundant if/else block just like the `format_eventbrite_events` function. 

However, I named this branch "fix/refactor-eventbrite-func" which is more specific. But if I remember correctly (and I'll confirm this), I believe uncommitted changes can be carried over to a new branch, so that may be a non-issue. Either way, I wanted to run this by you before I test and make a PR.

**Comment by allella** [comment]
Sure, feel free to clean things up. I'd suggest more, smaller branches and PRs since I'm the only one reviewing these and I'm not a Python guru.

You can also use _git stash save_ if you have uncommitted changes and want to save them and then start a branch and _git stash apply_ the changes to the new branch. Here are notes I have on git stash.

![image](https://user-images.githubusercontent.com/1777776/167162578-ccc0845e-f67e-48d3-ad13-e772b375b3cd.png)

**Comment by ramonaspence** [comment]
Oh thank you! That's very helpful. 

Alright, I'll finish this up tonight or tomorrow!

**Comment by ramonaspence** [comment]
Alright, just one more question for this. When an event is online, most of the location data is null. Do the null fields serve a purpose or would it be better for the online events to read `location: "Online Event"`? 

In the json+ld output, the location for an online event from meetup for reference:
```
"location": {
                    "@type": "Place",
                    "name": "Online event",
                    "address": {
                        "streetAddress": null,
                        "addressLocality": null,
                        "addressRegion": null,
                        "addressCountry": "",
                        "postalCode": null
                    },
                    "geo": {
                        "@type": "GeoCoordinates",
                        "latitude": null,
                        "longitude": null
                    }
                }
```

And eventbrite:
```
"location": {
                    "@type": "Place",
                    "name": null,
                    "address": {
                        "streetAddress": null,
                        "addressLocality": null,
                        "addressRegion": null,
                        "addressCountry": null,
                        "postalCode": null
                    },
                    "geo": {
                        "@type": "GeoCoordinates",
                        "latitude": null,
                        "longitude": null
                    }
                }
```

Since I'm not as experienced, I don't want to assume that the null fields aren't doing anything for search engines or other websites and apps that consume the API.

**Comment by allella** [comment]
That's a fair question. Since we're using Schema.org markup, it's probably something that's been though through and answered somewhere on the internet.  

Whether you'd remove the place, or use some other schema entity is probably the question.

Just quickly searching I see a "pending" type of https://schema.org/VirtualLocation
and  "schema place vs virtuallocation" has this from Google
https://developers.google.com/search/docs/advanced/structured-data/event

**Comment by allella** [comment]
Actually, that Google link may address this perfectly. Plus, it may address the case when an event is both physical and online.
https://developers.google.com/search/docs/advanced/structured-data/event

**Comment by ramonaspence** [comment]
Okay, neat! That seems like the direction we should be moving. However, since this is pending, perhaps it's best for us to bookmark this until it's implemented. I'm reading [Issue 1842](https://github.com/schemaorg/schemaorg/issues/1842) where a couple of people have specified that Google doesn't recognize `virtualLocation` as a valid location yet. 

I'm trying to verify that that is no longer true. Schema.org lists Issue 1842 as pending as of v11.0, but I don't see that it's been implemented yet, as of v14.0. I'm making a [comment](https://github.com/schemaorg/schemaorg/issues/1842#issuecomment-1126580125) on the issue to find out where they are in that process. 

Since, as of right now, we only have the Meetup events listing "Online Event" and it's under "name", I don't think that implementing `virtualLocation` will hinder search engines' capacity to use the data from our API. At the same time, I don't know how it might affect the other services that consume our API. If we implement this now, and have to change it later when Schema.org might implement a different name, it may become a hassle for those who are consuming the events API. Then again, it might be worthwhile hassle for everyone involved. 

Whew, sorry to be a bit long-winded on the topic. What do you think, @allella? Should we go ahead and start using `virtualLocation` for online events like the examples from Google?

**Comment by WeaverStever** [comment]
Regarding the question about virtuallocation. 

The Google Guidance is here:
https://developers.google.com/search/docs/advanced/structured-data/event

The schema is current with the Google implementaton.

Regards.

**Comment by allella** [comment]
@ramonaspence if you're not already too far down this road, then perhaps submit a PR for the initial issue, and then we can create a new Issue, referencing the conversation here, and a new PR for that JSON+LD work.

Thanks

**Comment by ramonaspence** [comment]
Okay, I'll do that. And as always, thank you for the guidance!

**Comment by allella** [comment]
@ramonaspence are you going to create a PR with the service and service_id changes I posted above?

I can do it, but I also don't want to complicate your branches and make you have to merge if you want to deal with it.

**Comment by ramonaspence** [comment]
@allella Yes! Sorry, I didn't mean to drop off the map. 

I'm making separate PR's for adding the service and service_id and for refactoring the function.
