### ISSUE TITLE
500 Error on the Tags

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#8]
@Nunie123 I tagged all the [OpenWorks related groups](https://data.openupstate.org/rest/organizations?tag_filter_id=1) and also hide the email field from the groups API.

Seems like as soon as I did that the [events API with &tags=1](https://nunes.online/api/gtc?tags=1) started returning a 500 error.

Maybe there's a special character in the markup for the newly tagged groups or some such?

**Comment by Nunie123** [comment]
I restarted the nginx web server and this appears to have fixed the issue.  I could not replicate locally, so I assume the issue was solely with the web server.  

I'm not familiar enough with nginx to know why a restart was needed, so I'm unsure how to prevent the issue from recurring.  If this issue happens again I can set up a cron job to restart nginx at midnight or something, but for now I'm considering this closed.
