### ISSUE TITLE
Roll events off when the end date/time passes, rather than the start time

### ISSUE THREAD

**Issue by allella** [codeforgreenville/upstate_tech_cal_service#9]
@Nunie123 I had the OpenWorks dashboard up on Thursday when we had three meetups there at the same time.

The security guard walked someone up and asked me to help the visitor find their meetup.  I looked at the dashboard to ask which group they were looking for and noticed the events had rolled off the list since the start time had passed.

Not sure if you have the end time, or if that's universally available, but it may be more practical to show an event up until it's over to avoid situations like this one where seeing the event info while it was happening would have helped.

Thoughts?

**Comment by Nunie123** [comment]
@allella ha, yeah, that makes sense.  I think the end time data is sketchy, but I can set it up so that all events for today will show up regardless if they have already started.

**Comment by Nunie123** [comment]
@allella This is deployed.  Rather than dealing with timezone issues, I just set the default start datetime to 1 day before the time of the request.

I'm not closing this yet, as there are no events today to verify this is working in production.  Everything appears to be working fine, but we will know if the changes are working on Monday.

Also, I can modify the default start date to any time you want, so if seeing the events from the past week, etc. would be helpful it would be a trivial change.

**Comment by allella** [comment]
@Nunie123 this looked good on the OpenWorks dashboard tonight. The Code For Greenville event was still listed when it was over.
